<?php
/**
 * Theme system functions.
 */

/*****************************************************************************
 * Alter Functions: Alter data before it's displayed.
 *****************************************************************************/

/**
 * Implements hook_css_alter().
 */
function purple_css_alter(&$css) {
  // Use Seven's vertical tabs style.
  if (isset($css['misc/vertical-tabs.css'])) {
    $css['misc/vertical-tabs.css']['data'] = backdrop_get_path('theme', 'seven') . '/vertical-tabs.css';
  }
}

/*****************************************************************************
 * Preprocess Functions: prepare variables for templates.
 *****************************************************************************/

/**
 * Override or insert variables into the page template.
 */
function purple_preprocess_page(&$variables) {
  // Add conditional CSS for IE8 and below.
  backdrop_add_css(path_to_theme() . '/ie.css', array('weight' => CSS_THEME, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
}

/**
 * Override or insert variables.
 */
function purple_preprocess_header(&$variables) {
  // Add the path for our images.
  $variables['path'] = base_path() . backdrop_get_path('theme', 'purple') . '/images/';
}

/**
 * Override or insert variables.
 */
function purple_preprocess_node(&$variables) {
  $variables['content']['links']['comment'] = array();
}

/*****************************************************************************
 * Theme Function Overrides: Change markup generated by Drupal.
 *****************************************************************************

/**
 * Remove extra.
 */
function purple_username($variables) {
  if (isset($variables['link_path'])) {
    // We have a link path, so we should generate a link using l().
    // Additional classes may be added as array elements like
    // $variables['link_options']['attributes']['class'][] = 'myclass';
    $output = l($variables['name'], $variables['link_path'], $variables['link_options']);
  }
  else {
    // Modules may have added important attributes so they must be included
    // in the output. Additional classes may be added as array elements like
    // $variables['attributes_array']['class'][] = 'myclass';
    $output = '<span' . backdrop_attributes($variables['attributes']) . '>' . $variables['name'] . '</span>';
  }
  return $output;
}
